# Specify a base image
FROM node:alpine
WORKDIR '/app'
# Install some depenendencies
COPY ./package.json ./
RUN npm config set proxy http://docker.for.win.localhost:3128
RUN npm config set https-proxy http://docker.for.win.localhost:3128
#RUN npm install -g create-react-app
RUN npm install
COPY . .
# Default command
CMD ["npm", "run", "start"] 